services:
  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    container_name: elysion-calendar-nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elysion-calendar-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elysion-calendar-backend
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    networks:
      - elysion-calendar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: elysion-calendar-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - elysion-calendar-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  elysion-calendar-network:
    driver: bridge
