services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: elysion-calendar-nginx
    depends_on:
      - frontend
      - backend
    networks:
      - elysion-calendar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elysion-calendar-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - elysion-calendar-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elysion-calendar-backend
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    networks:
      - elysion-calendar-network

networks:
  elysion-calendar-network:
    driver: bridge
