services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elysion-calendar-backend
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - REDIS_URL=redis://redis:6379/0
    networks:
      - elysion-calendar-network
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: elysion-calendar-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - elysion-calendar-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: elysion-calendar-redis
    networks:
      - elysion-calendar-network

networks:
  elysion-calendar-network:
    driver: bridge
